server:
  port: 9002

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd_ef
    username: root
    password: 1234
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

